###
### junand 11.03.2020
###

# printer3d/docker-compose.yaml

networks:

    proxy:
        external: true
        
services:

    octoprint:
        build:
          context: ./octoprint
        image: ${DOCKER_REGISTRY}my_octoprint
        container_name: octoprint
        restart: ${DOCKER_RESTART_POLICY}
        environment:
          - TZ=Europe/Berlin
        labels:
          - com.centurylinklabs.watchtower.enable=${WATCHTOWER_CHECK_BUILD_IMAGE}
          - "traefik.enable=true"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
          - "traefik.docker.network=proxy"
        volumes:
          - ~/docker/octoprint:/octoprint
        networks:
          - proxy
