###
### junand 11.03.2020
###

# printer3d/docker-compose.yaml

version: '3.3'

networks:

  proxy:
    external:
        name: proxy
        
services:

  octoprint:
    build:
      context: ./octoprint
      labels:
        com.centurylinklabs.watchtower.enable: "false"
    image: octoprint
    container_name: octoprint
    restart: "no"
    environment:
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.tls=false"
      - "traefik.http.routers.nodered.entrypoints=dontuse"
    volumes:
      - "~/docker/octoprint:/data"
    networks:
      - proxy
