###
### junand 11.03.2020
###

# printer3d/docker-compose.yaml

version: '3.3'

networks:

  proxy:
    external:
        name: proxy
        
services:

  octoprint:
    build:
      context: ./octoprint
    image: ${DOCKER_REGISTRY}my_octoprint
    container_name: octoprint
    restart: "no"
    environment:
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=proxy"
    volumes:
      - ~/docker/octoprint:/octoprint
    networks:
      - proxy
