# junand 29.03.2020

# from ct 08/2020 S. 166
# https://github.com/jamct/docker-log

FROM fluent/fluentd:edge-debian-armhf
USER root
#RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "3.5.2"]
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document"]
USER fluent