###
### junand 11.03.2020
###

# printer3d/docker-compose.yaml

version: '3.3'

networks:

  backbone:
    external:
        name: backbone
        
services:

    telegraf_logs:
        image: telegraf:latest
        container_name: telegraf_logs
        restart: "no"
        environment:
          - TZ=Europe/Berlin
          - INFLUX_TOKEN=${INFLUX_TOKEN}
        labels:
          - "traefik.enable=false"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ~/docker/docker/logging/telegraf_logs.conf:/etc/telegraf/telegraf.conf:ro
        networks:
          - backbone

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        restart: "no"
        environment:
          - TZ=Europe/Berlin
          - INFLUX_TOKEN=${INFLUX_TOKEN}
          - HOSTNAME=${HOSTNAME}
        labels:
          - "traefik.enable=false"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
        volumes:
          - ~/docker/docker/logging/telegraf.conf:/etc/telegraf/telegraf.conf:ro
          - ~/docker/traefik/ssl:/etc/ssl/certs/nodesathome:ro
        networks:
          - backbone
