###
### junand 11.03.2020
###

# printer3d/docker-compose.yaml

version: '3.3'

networks:

  proxy:
    external:
        name: proxy
        
  logging:
    external:
        name: logging
        
services:

    fluentd:
        build: 
            context: ./fluentd
            labels:
                com.centurylinklabs.watchtower.enable: "false"
        image: fluentd
        container_name: fluentd
        restart: "no"
        environment:
          - TZ=Europe/Berlin
        labels:
          - "traefik.enable=false"
        depends_on:
          - elasticsearch
        volumes:
          - ~/docker/docker/logging/fluentd:/fluentd/etc
          # for debug only
          #- ~/docker/fluentd/logs:/logs
          - /var/lib/docker/containers:/var/lib/docker/containers
        ports:
          - "127.0.0.1:24224:24224"
          - "127.0.0.1:24224:24224/udp"        
        networks:
          - logging

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0-arm64
        container_name: elasticsearch
        restart: "no"
        environment:
          - HOSTNAME
          - TZ=Europe/Berlin
          - "discovery.type=single-node"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
          - "traefik.docker.network=proxy"
        expose:
          - "9200"
        volumes:
          - ~/docker/elasticsearch:/usr/share/elasticsearch/data
          - ~/docker/docker/logging/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
        networks:
          - proxy
          - logging

    kibana:
        #image: virb3/kibana:7-arm64
        image: virb3/kibana:7-nosecurity-arm64
        container_name: kibana
        restart: "no"
        environment:
          - TZ=Europe/Berlin
          ###- NODE_OPTIONS=--max_old_space_size=1536
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
          - "traefik.docker.network=proxy"
        volumes:
          - ~/docker/docker/logging/kibana.yaml:/usr/share/kibana/config/kibana.yml
        networks:
          - logging
          - proxy
