###
### junand 11.03.2020
###

# traefik/docker-compose.yaml

version: '3.3'

networks:

  proxy:
    external:
        name: proxy

  metrics:
    external:
        name: metrics

services:

  traefik:
    image: traefik
    container_name: traefik
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
      - PARENT_HOSTNAME=${HOSTNAME}
    depends_on:
      - whoami
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "~/docker/docker/traefik/traefik.yaml:/etc/traefik/traefik.yml"
      - "~/docker/docker/traefik/dynamic:/etc/traefik/dynamic"
      - "~/docker/traefik/ssl:/etc/ssl/nodesathome"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "8883:8883"
      - "10001:10001"
      - "10002:10002"
      - "8123:8123"
    networks:
      - proxy
      - metrics

  whoami:
    # a container that exposes an API to show its IP address
    image: containous/whoami
    container_name: whoami
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=false"
      - "traefik.http.routers.whoami.entrypoints=dontuse"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
