###
### junand 14.03.2020
###

global:
    checkNewVersion: true
    sendAnonymousUsage: false
    
api:
    insecure: true
    dashboard: true
    debug: true
    
providers:
    file:
        directory: /etc/traefik/dynamic
        watch: true
    docker:
        watch: true
        exposedByDefault: false
    
entryPoints:
    web:
        address: ":80"
    web_secure:
        address: ":443"
    mqtt:
        address: ":1883"
    mqtt_secure:
        address: ":8883"
        
log:
    # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
    level: DEBUG 