###
### junand 12.08.2019
###

version: "3.3"

networks:

  mosquitto-net:
  influxdb-net:
  nginx-net:
  prometheus-net:
  
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: "no"
    depends_on:
      - cadvisor
      - node-exporter
    volumes:
      - "~/docker/prometheus/data:/prometheus"
      - "~/docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - prometheus-net
      
  cadvisor:
    image: budry/cadvisor-arm
    container_name: cadvisor
    restart: "no"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    ports:
      - "8080:8080"
    networks:
      - prometheus-net
      
  node-exporter:
    image: prom/node-exporter
    command: "--collector.textfile.directory=/data"
    container_name: node-exporter
    restart: "no"
    volumes:
      - "/var/lib/node_exporter/textfile_collector:/data"
    ports:
      - "9100:9100"
    networks:
      - prometheus-net

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: "no"
    volumes:
      - "~/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "~/docker/mosquitto/data:/mosquitto/data"
      - "~/docker/mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mosquitto-net
      
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: "no"
    volumes:
      - "~/docker/influxdb:/var/lib/influxdb"
    ports:
      - "8086:8086"
    networks:
      - influxdb-net
      
  hass:
    image: homeassistant/raspberrypi3-homeassistant:stable
    container_name: hass
    restart: "no"
    depends_on:
      - mosquitto
      - influxdb
      - octoprint
    environment:
      - PARENT_HOSTNAME=${HOSTNAME}
      - HA_TITLE=Mein Zuhause @${HOSTNAME}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "~/docker/home-assistant:/config"
    ports:
      - "8123:8123"
    networks:
      - mosquitto-net
      - influxdb-net
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: "no"
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - "~/docker/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - influxdb-net
      - prometheus-net
      
  nginx:
    image: tobi312/rpi-nginx
    container_name: nginx
    restart: "no"
    volumes:
      - "~/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "~/docker/nginx/log:/var/log/nginx"
      - "~/docker/nginx/html:/usr/share/nginx/html"
      - "~/docker/nginx/tileboard:/usr/share/nginx/html/tileboard"
    ports:
      - "80:80"

  nodered:
    ###image: nodered/node-red-docker:rpi
    image: nodered/node-red
    container_name: nodered
    restart: "no"
    depends_on:
      - influxdb
      - mosquitto
    environment:
      - TZ=Europe/Berlin
      - PARENT_HOSTNAME=${HOSTNAME}
    volumes:
      - "~/docker/nodered:/data"
      - "~/docker/nginx:/var/www/html"
      - "~/GIT/brewery/recipes:/data/recipes" 
    ports:
      - "1880:1880"
      - "10001:10001"
    networks:
      - mosquitto-net
      - influxdb-net

  octoprint:
    build: ./octoprint
    image: octoprint
    container_name: octoprint
    restart: "no"
    depends_on:
      - mosquitto
    volumes:
      - "~/docker/octoprint:/data"
    ports:
      - "1337:80"
    networks:
      - nginx-net
