###
### junand 14.03.2020
###

tls:

    # https://ssl-config.mozilla.org/#server=traefik&config=intermediate
    # due to Go limitations, it is highly recommended that you use an ECDSA
    # certificate, or you may experience compatibility issues    
        
    stores:
        default:
            defaultCertificate:
                keyFile: /etc/ssl/nodesathome/certificate-key-{{ env "PARENT_HOSTNAME" }}.pem
                certFile: /etc/ssl/nodesathome/certificate-pub-{{ env "PARENT_HOSTNAME" }}.pem
        
    options:
        intermediate:
            minVersion: "VersionTLS12"
            cipherSuites:
              - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
              - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
              - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
              - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
              - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
              - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
              
http:

    routers:
        web:
            entryPoints: 
              - 'web'
            rule: 'HostRegexp(`{any:.*}`)'
            middlewares:
              - web-redirect
              # - hsts-header
            service: redirect-all
        api:
            entryPoints: 
              - 'web_secure'
            # rule: '( Host(`{{ env "PARENT_HOSTNAME" }}`) || Host(`192.168.2.16`) ) && ( PathPrefix(`/api`) || PathPrefix(`/dashboard`) )'
            rule: '( Host(`{{ env "PARENT_HOSTNAME" }}`) ) && ( PathPrefix(`/api`) || PathPrefix(`/dashboard`) )'
            service: api@internal
            middlewares:
              - pokemonnet
            tls:
                options: intermediate
        whoami:
            entryPoints: 
              - 'web_secure'
            # rule: '( Host(`{{ env "PARENT_HOSTNAME" }}`) || Host(`192.168.2.16`) ) && PathPrefix(`/whoami`)'
            rule: '( Host(`{{ env "PARENT_HOSTNAME" }}`) ) && PathPrefix(`/whoami`)'
            middlewares:
              - pokemonnet
              #- onlysurface
              # - hsts-header
            service: whoami-traefik@docker
            tls:
                options: intermediate
            
    middlewares:
        web-redirect:
            redirectScheme:
                scheme: https
        hsts-header:
            headers:
                customResponseHeader:
                    Strict-Transport-Security: "max-age=63072000"
        auth:
            basicAuth:
                users:
                  - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
                  - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"
        onlysurface:
            ipWhiteList:
                sourceRange:
                  - 192.168.2.134/32
        pokemonnet:
            ipWhiteList:
                sourceRange:
                  - 192.168.2.0/24
                  
    services:
        redirect-all:
            loadBalancer:
                servers:
                  - url: ''

tcp:

    routers:
        mosquitto:
            entryPoints: 
              - 'mqtt'
            # rule: 'HostSNI(`{{ env "PARENT_HOSTNAME" }}`)'
            rule: HostSNI(`*`)
            middlewares:
              - pokemonnet
            service: mosquitto-traefik@docker
        mosquitto_secure:
            entryPoints:
              - 'mqtt_secure'
            rule: HostSNI(`*`)
            middlewares:
              - pokemonnet
              # - hsts-header
            service: mosquitto-traefik@docker
            tls:
                options: intermediate
            
    middlewares:
        pokemonnet:
            ipWhiteList:
                sourceRange:
                  - 192.168.2.0/24
