###
### junand 12.08.2019
###

version: "3.3"

networks:

  prometheus-net:
  
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: "no"
    depends_on:
      - cadvisor
      - node-exporter
    volumes:
      - "~/docker/prometheus/data:/prometheus"
      - "~/docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - prometheus-net
      
  cadvisor:
    image: budry/cadvisor-arm
    container_name: cadvisor
    restart: "no"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    ports:
      - "8080:8080"
    networks:
      - prometheus-net
      
  node-exporter:
    image: prom/node-exporter
    command: "--collector.textfile.directory=/data"
    container_name: node-exporter
    restart: "no"
    volumes:
      - "/var/lib/node_exporter/textfile_collector:/data"
    ports:
      - "9100:9100"
    networks:
      - prometheus-net
      
