###
### junand 25.12.2019
###

# admin/docker-compose.yaml

version: "3.3"

networks:

  admin:
    external:
        name: admin

services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #  - "~/docker/watchtower/config.json:/config.json"
    command: --debug --include-stopped --schedule "0 0 1 * * ${WATCHTOWER_SCHEDULE_DAY}"     # 6 = saturday morning 1:00 utc, production mode
    # more options
    #   --monitor-only -> without container restart
    #   --interval 60  -> every minute
    environment:
      - TZ="Europe/Berlin"
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${HOSTNAME}@jungierek.de 
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_MAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_MAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_MAIL_SERVER_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_MAIL_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_MAIL_PW}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    networks:
      - admin


# remove images who are older than ...
# docker system prune --filter "until=240h"