###
### junand 10.10.2025
###

# ai/docker-compose.yaml

x-deploy_nvidia: &deploy_nvidia
    deploy:
        resources:
            reservations:
                devices:
                  - driver: nvidia
                    count: all
                    capabilities:
                      - gpu
                      - utility
                      - compute

x-ollama_image_jetson: &ollama_image_jetson
    image: ${DOCKER_REGISTRY}dustynv/ollama:0.6.8-r36.4-cu126-22.04
    volumes:
      - ~/docker/ollama:/root/.ollama  # Persistente Speicherung der Modelle
      - ~/docker/docker/ai/start_ollama_and_idle.sh:/opt/start_ollama_and_idle.sh
    entrypoint: ["/opt/start_ollama_and_idle.sh"]

x-ollama_image_wsl2: &ollama_image_wsl2
    image: ${DOCKER_REGISTRY}dustynv/ollama:0.6.8-r36.4-cu126-22.04
    volumes:
      - ~/docker/ollama:/root/.ollama  # Persistente Speicherung der Modelle

x-ollama_container: &ollama_container
    container_name: ollama
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - TZ=Europe/Berlin
      - OLLAMA_LOG_LEVEL=debug
      - OLLAMA_MODELS=/root/.ollama/models
      - JETSON_JETPACK=6
    labels:
      - "traefik.enable=false"
    ports:
      - "11434:11434"  # Standard-Port für die API
    networks:
      - backbone

### Wyoming Piper Containers
### https://github.com/dusty-nv/jetson-containers/tree/master/packages/smart-home/wyoming/wyoming-piper
###
x-piper-jetson: &piper_jetson
    image: dustynv/wyoming-piper:master-r36.2.0

x-piper-wsl2: &piper_wsl2
    image: wyoming-piper-gpu
    build:
      context: ./wyoming-piper-gpu

x-piper: &piper_container
    container_name: piper
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - TZ=Europe/Berlin
      - PIPER_VOICE=de_DE-thorsten-high
    labels:
      - "traefik.enable=false"
    volumes:
      - ~/docker/piper/data:/data
    ports:
      - "10201:10200"
    runtime: nvidia
    << : *deploy_nvidia

x-whisper-jetson: &whisper_jetson
    image: dustynv/wyoming-whisper:latest-r36.2.0
    volumes:
      - ~/docker/whisper/models:/share/whisper
      - ~/docker/whisper/data:/data

# https://community.home-assistant.io/t/whisper-on-gpu/903694
x-whisper-wsl2: &whisper_wsl2
    image: lscr.io/linuxserver/faster-whisper:gpu
    volumes:
      - ~/docker/whisper/data:/config
      - ~/docker/whisper/run:/etc/s6-overlay/s6-rc.d/svc-whisper/run

x-whisper: &whisper_container
    container_name: whisper
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - WHISPER_MODEL=large-v3
      - WHISPER_LANG=de
      - WHISPER_BEAM=20
      - LOG_LEVEL=DEBUG
    labels:
      - "traefik.enable=false"
    ports:
      - 10300:10300
      - 10300:10300/tcp
    # network_mode: host
    runtime: nvidia
    << : *deploy_nvidia

networks:

  proxy:
    external: true

  backbone:
    external: true

services:

    n8n:
        image: ${DOCKER_REGISTRY}n8nio/n8n:latest
        container_name: n8n
        restart: ${DOCKER_RESTART_POLICY}
        environment:
          - TZ=Europe/Berlin
          - GENERIC_TIMEZONE=Europe/Berlin
          - N8N_HOST=${HOSTNAME}
          - N8N_PORT=5678
          - N8N_PROTOCOL=https
          - N8N_SECURE_COOKIE=false
          - WEBHOOK_URL=http://localhost:5678/
          - N8N_PATH=/n8n/
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
          - "traefik.docker.network=proxy"
        # depends_on:
        #   - ollama
        volumes:
          - ~/docker/n8n:/home/node/.n8n
          - ~/docker/n8n/certificates:/opt/custom_certificates:ro
        networks:
          - proxy
          - backbone

    ollama-jetson:
        << : [*ollama_image_jetson, *ollama_container]

    ollama-wsl2:
        << : [*ollama_image_wsl2, *ollama_container]

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        restart: ${DOCKER_RESTART_POLICY}
        environment:
          - TZ=Europe/Berlin
          - OLLAMA_BASE_URL=http://ollama:11434
          - WEBUI_AUTH=False
          - PORT=3000
        expose:
          - "3000"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dontuse.entrypoints=dontuse"
          # - "traefik.http.services.open-webui-ai.loadbalancer.server.port=8080"
          - "traefik.docker.network=proxy"
        volumes:
          - ~/docker/openwebui:/app/backend/data
        networks:
          - proxy
          - backbone

    whisper-jetson:
        << : [*whisper_jetson, *whisper_container]

    whisper-wsl2:
        << : [*whisper_wsl2, *whisper_container]

    piper-jetson:
        << : [*piper_jetson, *piper_container]

    piper-wsl2:
        << : [*piper_wsl2, *piper_container]
