###
### junand 11.03.2020
###

# proxy/docker-compose.yaml

version: '3.3'

networks:

  proxy:
    external:
        name: proxy

  metrics:
    external:
        name: metrics

services:

  traefik:
    image: ${DOCKER_REGISTRY}traefik
    container_name: traefik
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
      - PARENT_HOSTNAME=${HOSTNAME}
    depends_on:
      - whoami
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "~/docker/docker/proxy/traefik.yaml:/etc/traefik/traefik.yml"
      - "~/docker/docker/proxy/dynamic:/etc/traefik/dynamic"
      - "~/docker/traefik/ssl:/etc/ssl/nodesathome"
    ports:
      - "80:80"             # http
      - "443:443"           # htpps
      - "1883:1883"         # mqtt
      - "8883:8883"         # mqtts
      - "10001:10001"       # luatrace (deprecated)
      - "10002:10002"       # luatrace secure
      - "514:514"           # syslog
      - "514:514/udp"       # syslog
      - "5000:5000"         # private docker registry secure
      # - "6514:6514"         # syslog secure
      - "8123:8123"         # home assistant secure
      - "8086:8086"         # influxdb secure
      - "3493:3493"         # upsd
    networks:
      - proxy
      - metrics

  whoami:
    # a container that exposes an API to show its IP address
    image: ${DOCKER_REGISTRY}containous/whoami
    container_name: whoami
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
