###
### junand 14.03.2020
###

global:

    checkNewVersion: true
    sendAnonymousUsage: false

# tracing:

    # jaeger:
        # samplingServerURL: http://192.168.2.134:5778/sampling
        # samplingType: const
        # samplingParam: 1.0

api:

    insecure: false
    dashboard: true
    debug: true

providers:

    file:
        directory: /etc/traefik/dynamic
        watch: true

    docker:
        watch: true
        exposedByDefault: false

entryPoints:

    web:
        address: ":80"

    web_secure:
        address: ":443"

    registry:
        address: ":5000"
        transport:
            respondingTimeouts:
                readTimeout: 0      # default is 60 sec timeout for responding, this is to small for pushing large images like home assistant to the registry

    upsd:
        address: ":3493"

    litellm:
        address: ":4000"

metrics:

    prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true

log:
    # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
    level: INFO
    format: json

accessLog: {}
