###
### junand 25.08.2020
###

# wsl2/docker-compose.yaml

volumes:
    portainer_data:

networks:
    admin:
        external: true

services:

    ### free business license for 5 nodes
    portainer:
        # image: portainer/portainer-ce
        image: portainer/portainer-ee:latest
        # image: portainer/portainer-ee:2.15.0
        container_name: portainer
        environment:
          - TZ=Europe/Berlin
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
          - "~/docker/traefik/ssl:/etc/ssl/nodesathome"
        command: --sslkey /etc/ssl/nodesathome/certificate-key-${HOSTNAME}.pem --sslcert /etc/ssl/nodesathome/certificate-pub-${HOSTNAME}.pem --sslcacert /etc/ssl/nodesathome/ca-root-nodesathome.pem
        ports:
          - 9443:9443
        networks:
          - admin

    nodemcu-esp32:
        build:
          context: ./nodemcu
          labels:
            com.centurylinklabs.watchtower.enable: "false"
        image: nodemcu-builder
        container_name: nodemcu-esp32
        restart: "no"
        environment:
          - TZ=Europe/Berlin
        labels:
          - "traefik.enable=false"
        volumes:
          - ~/GIT/nodemcu-firmware-esp32:/opt/nodemcu-firmware

    nodemcu-esp8266:
        build:
          context: ./nodemcu
          labels:
            com.centurylinklabs.watchtower.enable: "false"
        image: nodemcu-builder
        container_name: nodemcu-esp8266
        restart: "no"
        environment:
          - TZ=Europe/Berlin
        labels:
          - "traefik.enable=false"
        volumes:
          - ~/GIT/nodemcu-firmware-esp8266:/opt/nodemcu-firmware

    qtcreator:
        build:
          context: ./qtcreator
          labels:
            com.centurylinklabs.watchtower.enable: "false"
        image: qtcreator
        container_name: qtcreator
        restart: "no"
        environment:
          - TZ=Europe/Berlin
          - DISPLAY=host.docker.internal:0.0
        labels:
          - "traefik.enable=false"
        volumes:
          - "/tmp/.X11-unix:/tmp/.X11-unix"
          - "/home/${USER}:/home/${USER}"
        command: qtcreator
