###
### junand 10.10.2025
### containerized AI services for Nvidia Jetson AGX Thor 128GB

# ai/docker-compose.yaml

x-deploy_nvidia: &deploy_nvidia
    deploy:
        resources:
            reservations:
                devices:
                  - driver: nvidia
                    count: all
                    capabilities:
                      - gpu
                      - utility
                      - compute

services:

    ollama-wsl2:
        image: ${DOCKER_REGISTRY}dustynv/ollama:0.6.8-r36.4-cu126-22.04
        container_name: ollama-wsl2
        restart: unless-stopped
        environment:
          - TZ=Europe/Berlin
          - OLLAMA_NO_CLOUD=1
          - OLLAMA_LOG_LEVEL=debug
          - OLLAMA_MODELS=/root/.ollama/models
          - JETSON_JETPACK=6
        labels:
          - "traefik.enable=false"
        volumes:
          - ~/docker/ollama:/root/.ollama  # Persistente Speicherung der Modelle
          - ~/docker/docker/ai/start_ollama_and_idle.sh:/opt/start_ollama_and_idle.sh
        ports:
          - "11434:11434"  # Standard-Port für die API
        # entrypoint: ["/opt/start_ollama_and_idle.sh"]
        runtime: nvidia
        << : *deploy_nvidia

    ollama-nano:
        image: ${DOCKER_REGISTRY}dustynv/ollama:0.6.8-r36.4-cu126-22.04
        container_name: ollama-nano
        restart: unless-stopped
        environment:
          - TZ=Europe/Berlin
          - OLLAMA_NO_CLOUD=1
          - OLLAMA_LOG_LEVEL=debug
          - OLLAMA_MODELS=/root/.ollama/models
          - JETSON_JETPACK=6
          - OLLAMA_NUM_CTX=1024
        labels:
          - "traefik.enable=false"
        volumes:
          - ~/docker/ollama:/root/.ollama  # Persistente Speicherung der Modelle
          - ~/docker/docker/ai/start_ollama_and_idle.sh:/opt/start_ollama_and_idle.sh
        ports:
          - "11434:11434"  # Standard-Port für die API
        entrypoint: ["/opt/start_ollama_and_idle.sh"]
        runtime: nvidia
        << : *deploy_nvidia

    ollama-thor:
        image: ollama:r39.1.arm64-sbsa-cu132-24.04-ollama
        container_name: ollama-thor
        restart: unless-stopped
        environment:
          - TZ=Europe/Berlin
          - OLLAMA_NO_CLOUD=1
          - OLLAMA_LOG_LEVEL=debug
          - OLLAMA_MODELS=/root/.ollama/models
          - OLLAMA_MAX_LOADED_MODELS=5
          - OLLAMA_FLASH_ATTENTION=1
          - OLLAMA_KV_CACHE_TYPE=q8_0
          - OLLAMA_NUM_PARALLEL=2
          - OLLAMA_NUM_GPU_LAYERS=999
        labels:
          - "traefik.enable=false"
        volumes:
          - ~/docker/ollama:/root/.ollama  # Persistente Speicherung der Modelle
          - ~/docker/docker/ai/start_ollama_and_idle.sh:/opt/start_ollama_and_idle.sh
        ports:
          - "11434:11434"  # Standard-Port für die API
        entrypoint: ["/opt/start_ollama_and_idle.sh"]
        # runtime: nvidia
        # << : *deploy_nvidia
