###
### junand 11.03.2020
###

# printer3d/docker-compose.yaml

version: '3.8'

networks:

    proxy:
        external:
            name: proxy
        
services:

    mkdocs-material:
        build:
            context: ./mkdocs-material
        labels:
            com.centurylinklabs.watchtower.enable: "false"
        image: mkdocs-material
        container_name: build-mkdocs-material
