###
### junand 11.03.2020
###

# metrics/docker-compose.yaml

version: '3.8'

networks:

  proxy:
    external:
        name: proxy

  metrics:
    external:
        name: metrics

  backbone:
    external:
        name: backbone

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=metrics"
    depends_on:
      - cadvisor
      - node-exporter
    volumes:
      - "~/docker/prometheus/data:/prometheus"
      - "~/docker/docker/metrics/prometheus.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - metrics

  cadvisor:
    image: zcube/cadvisor
    container_name: cadvisor
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=metrics"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      - metrics

  node-exporter:
    image: prom/node-exporter
    command: "--collector.textfile.directory=/data"
    container_name: node-exporter
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=metrics"
    volumes:
      - "/var/lib/node_exporter/textfile_collector:/data"
    networks:
      - metrics

  fritzbox:
    build:
      context: ./fritzbox
      labels:
        com.centurylinklabs.watchtower.enable: "false"
    image: fritzbox
    container_name: fritzbox
    restart: "no"
    environment:
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=proxy"
    networks:
      - backbone

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: "no"
    environment:
      - TZ="Europe/Berlin"
      - GF_SERVER_DOMAIN=${HOSTNAME}
      - GF_SERVER_ROOT_URL=https://${HOSTNAME}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dontuse.entrypoints=dontuse"
      - "traefik.docker.network=proxy"
    depends_on:
      - prometheus
    volumes:
      - "~/docker/grafana:/var/lib/grafana"
    networks:
      - proxy
      - metrics
      - backbone
